package id.barkost.waris;

public class Varr {
	public static int 
		iHarta,
		tarikah = 0,
		hak1 = 0,
		hak2 = 0,
		hak3 = 0,
		hak4 = 0,
		iJumlahBapak = 0, 
		iJumlahIbu = 0, 
		iJumlahSuami = 0, 
		iJumlahIstri = 0, 
		iJumlahAnakLaki = 0, 
		iJumlahAnakPerempuan = 0, 
		iJumlahCucuLaki = 0, 
		iJumlahCucuPerempuan = 0, 
		iJumlahKakek = 0, 
		iJumlahNenekBapak = 0, 
		iJumlahNenekIbu = 0, 
		iJumlahNenekKakek = 0,
		iJumlahSaudaraKandung = 0, 
		iJumlahSaudariKandung = 0, 
		iJumlahSaudaraSebapak = 0, 
		iJumlahSaudaraSeibu = 0, 
		iJumlahSaudariSebapak = 0, 
		iJumlahSaudariSeibu = 0, 
		iJumlahPutraSaudaraKandung = 0, 
		iJumlahPutraSaudaraSebapak = 0, 
		iJumlahPamanKandung = 0, 
		iJumlahPamanSebapak = 0, 
		iJumlahPutraPamanKandung = 0, 
		iJumlahPutraPamanSebapak = 0, 
		iJumlahPriaMerdekakan = 0, 
		iJumlahWanitaMerdekakan = 0;
	
	public static boolean iCucuLaki = false,
			iCucuPerempuan = false,
			iKakek = false,
			iNenekBapak = false,
			iNenekIbu = false,
			iNenekKakek = false,
			iSaudaraKandung = false,
			iSaudariKandung = false,
			iSaudaraSebapak = false,
			iSaudaraSeibu = false,
			iSaudariSebapak = false,
			iSaudariSeibu = false,
			iPutraSaudaraKandung = false,
			iPutraSaudaraSebapak = false,
			iPamanKandung = false,
			iPamanSebapak = false,
			iPutraPamanKandung = false,
			iPutraPamanSebapak = false,
			iPriaMerdekakan = false,
			iWanitaMerdekakan = false;
}
